arrowParens: avoid
importOrder:
    - "<THIRD_PARTY_MODULES>"
    - "^[./]"
importOrderSeparation: true
plugins:
    - "@trivago/prettier-plugin-sort-imports"
    - "prettier-plugin-tailwindcss"
tabWidth: 4
