export { default as BackSvg } from "./BackSvg";
export { default as CloseSvg } from "./CloseSvg";
export { default as EmailSvg } from "./EmailSvg";
export { default as HamburgerMenuSvg } from "./HamburgerMenuSvg";
export { default as LogOutSvg } from "./LogOutSvg";
export { default as PasswordSvg } from "./PasswordSvg";
export { default as SearchSvg } from "./SearchSvg";
export { default as UserCircleSvg } from "./UserCircleSvg";
export { default as UserSvg } from "./UserSvg";
